Customizable http and https proxy addrs
stripe/goproxy pull request #22
Opened 2023-11-08 23:51 UTC by xieyuxi-stripe

### Summary
Allow setting the httpProxyAddr and httpsProxyAddr directly in `ProxyHttpServer` constructor. If these addresses are not set, use the default values from environment. 

### Motivation
stripe/smokescreen uses this library for the proxy server. Currently, the only way to set the transport proxy for smokescreen are [setting the proxy from environment](https://github.com/stripe/goproxy/blob/master/proxy.go#L192), which requires us to set the environment variables like HTTP_PROXY, HTTPS_PROXY. We would like to have a more robust way of configuring the smokescreen server's transport proxy. Thus we are adding the transport proxy address as another configurations for the smokescreen server and the goproxy library it uses underneath.

2023-11-09 17:33 UTC, cds2-stripe requested changes
I left a few comments and I have a few more, but before we can restructure this we should align on whether we want the env variables or configuration to take precedence.

2023-11-09 17:33 UTC, cds2-stripe commented on proxy.go
> +	cfg := httpproxy.FromEnvironment()
I'm not sure about silently overriding environment proxy variables. WDYT?

2023-11-09 17:33 UTC, cds2-stripe commented on proxy.go
> +	cfg := httpproxy.FromEnvironment()
Also could we name this something to signal what it actually is instead of just `cfg`?

2023-11-09 18:54 UTC, xieyuxi-stripe commented
I am planning to make the configuration take precedence and fall back to environment variable when configuration is not set.

2023-11-13 21:49 UTC, cds2-stripe approved these changes

2023-11-13 21:53 UTC, merged